name: main-workflow

on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: true
        type: string
      sonar_token:
        required: true
        type: string
permissions: write-all

jobs:
  
  build-and-test:
    uses: ./.github/workflows/maven-build-and-test.yml
  
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if SONAR_TOKEN is present
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "SONAR_TOKEN is not set"
          else
            ${{ inputs.sonar_token }}="${{ secrets.SONAR_TOKEN }}"
          fi

  sonarqube-scan:
    needs: build-and-test
    uses: ./.github/workflows/sonarqube-scan-java.yml
    with:
      sonar_project_key: ${{ inputs.sonar_project_key }}
      sonar_token: ${{ inputs.sonar_token }}

  ecr-login-and-push:
    needs: sonarqube-scan
    uses: ./.github/workflows/ecr-login-and-push.yml

  deploy-dev:
    needs: ecr-login-and-push
    uses: ./.github/workflows/deploy-dev.yml

  deploy-staging:
    needs: deploy-dev
    uses: ./.github/workflows/deploy-staging.yml

  manual-approve:
    needs: deploy-staging
    uses: ./.github/workflows/manual-approve.yml

  deploy-prod:
    needs: manual-approve
    uses: ./.github/workflows/deploy-prod.yml
