name: main-frontend-workflow

on:
  workflow_call:
    inputs:
      sonar_project_key:
        required: true
        type: string
      
    #secrets:
      #AWS_ACCESS_KEY_ID:
        #required: true
      #AWS_SECRET_ACCESS_KEY:
        #required: true
      #AWS_SESSION_TOKEN:
        #required: true
      #AWS_ACCOUNT_ID:
        #required: true
permissions: write-all
jobs:
  
  build-and-test:
    uses: ./.github/workflows/vue-build-and-test.yml
  
  
  sonarqube-scan:
    needs: build-and-test
    uses: ./.github/workflows/sonarqube-scan-vue.yml
    with:
      sonar_project_key: ${{ inputs.sonar_project_key }}
    secrets: inherit  

  
  #deploy-dev:
    #needs: build-and-test
    #uses: ./.github/workflows/deploy-S3-dev.yml
    #secrets: inherit

  #deploy-staging:
    #needs: deploy-dev
    #uses: ./.github/workflows/deploy-S3-staging.yml
    #secrets: inherit

  #manual-approve:
    #needs: deploy-staging
    #uses: ./.github/workflows/manual-approve.yml
    #secrets: inherit

  #deploy-prod:
    #needs: manual-approve
    #uses: ./.github/workflows/deploy-s3-prod.yml
    #secrets: inherit
