name: Manual Approve

on:
  workflow_call:
env:
  APPROVERS: "zionweb,Lucas991999, deploy-approvers"
jobs:
  approve:
    
    runs-on: ubuntu-latest
    steps:
      - run: echo 'environment ${{ inputs.CI_ENV }}'
      - uses: trstringer/manual-approval@v1.9.0
        with:
          secret: ${{ secrets.TOKEN_API }}
          approvers: ${{ env.APPROVERS }}
          issue-title: "APROBADO MANUALMENTE"
          exclude-workflow-initiator-as-approver: false
          # additional-approved-words: 'si'
          # additional-denied-words: 'no'
          minimum-approvals: 1
